const CREATE = 'CREATE';
const RETRIEVE = 'RETRIEVE';
const UPDATE = 'UPDATE';

const CHANGE_USERNAME = 'CHANGE_USERNAME';
const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
const CHANGE_PASSWORD2 = 'CHANGE_PASSWORD2';
const CHANGE_EMAIL = 'CHANGE_EMAIL';

const SAVE = 'SAVE';

const TO_DELETE = 'TO_DELETE';  //delete is reserved word
const VERIFY_DELETE = 'VERIFY_DELETE';

const EXIT = 'EXIT';
const START_SAVE = 'START_SAVE';
const FINISH_SAVE = 'FINISH_SAVE';

module.exports = {
    CREATE,
    RETRIEVE,
    UPDATE,

    CHANGE_USERNAME,
    CHANGE_PASSWORD,
    CHANGE_PASSWORD2,
    CHANGE_EMAIL,

    SAVE,

    TO_DELETE,
    VERIFY_DELETE,

    EXIT,
    START_SAVE,
    FINISH_SAVE,
}