const SUCCESS_SIGNIN = 'SUCCESS_SIGNIN';
const SUCCESS_SIGNOUT = 'SUCCESS_SIGNOUT';

const CHANGE_USERNAME = 'CHANGE_USERNAME';
const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
const CHANGE_PASSWORD2 = 'CHANGE_PASSWORD2';
const CHANGE_EMAIL = 'CHANGE_EMAIL';

const LABELS = {
    FORM_USERS_TITLE: 'ΧΡΗΣΤΕΣ',
    FORM_SIGNUP_TITLE: 'ΕΓΓΡΑΦΗ ΧΡΗΣΤΗ',
    FORM_SIGNIN_TITLE: 'ΣΥΝΔΕΣΗ ΧΡΗΣΤΗ',
    FORM_SIGNOUT_TITLE: 'ΑΠΟΣΥΝΔΕΣΗ ΧΡΗΣΤΗ',
    INPUT_USERNAME: 'ΟΝΟΜΑ ΧΡΗΣΤΗ',
    INPUT_PASSWORD: 'ΚΩΔΙΚΟΣ ΕΙΣΟΔΟΥ',
    INPUT_PASSWORD2: 'ΕΠΑΝΑΛΗΨΗ ΚΩΔΙΚΟΥ',
    INPUT_EMAIL: 'EMAIL',
};

module.exports = {
    SUCCESS_SIGNIN,
    SUCCESS_SIGNOUT,

    CHANGE_USERNAME,
    CHANGE_PASSWORD,
    CHANGE_PASSWORD2,
    CHANGE_EMAIL,

    LABELS,
};
