const SELECT_CREATE = 'SELECT_CREATE';
const VERIFY_CREATE = 'VERIFY_CREATE';

const SELECT_RETRIEVE = 'SELECT_RETRIEVE';
const VERIFY_RETRIEVE = 'VERIFY_RETRIEVE';

const SELECT_UPDATE = 'SELECT_UPDATE';
const VERIFY_UPDATE = 'VERIFY_UPDATE';

const SELECT_DELETE = 'SELECT_DELETE';
const VERIFY_DELETE = 'VERIFY_DELETE';

const EXIT = 'EXIT';

const BEFORE_REQUEST = 'BEFORE_REQUEST';
const AFTER_REQUEST = 'AFTER_REQUEST';

module.exports = {
    SELECT_CREATE,
    VERIFY_CREATE,

    SELECT_RETRIEVE,
    VERIFY_RETRIEVE,

    SELECT_UPDATE,
    VERIFY_UPDATE,

    SELECT_DELETE,
    VERIFY_DELETE,

    EXIT,

    BEFORE_REQUEST,
    AFTER_REQUEST,
}