const SELECT_CREATE = 'SELECT_CREATE';
const SELECT_RETRIEVE = 'SELECT_RETRIEVE';
const SELECT_UPDATE = 'SELECT_UPDATE';
const SELECT_DELETE = 'SELECT_DELETE';
const CLOSE_FORM = 'CLOSE_FORM';
const GO_HOME = 'GO_HOME';

const VERIFY_CREATE = 'VERIFY_CREATE';
const VERIFY_RETRIEVE = 'VERIFY_RETRIEVE';
const VERIFY_UPDATE = 'VERIFY_UPDATE';
const VERIFY_DELETE = 'VERIFY_DELETE';
const CLOSE_DATA = 'CLOSE_FORM';

const BEFORE_REQUEST = 'BEFORE_REQUEST';
const AFTER_REQUEST = 'AFTER_REQUEST';

module.exports = {
    SELECT_CREATE,
    SELECT_RETRIEVE,
    SELECT_UPDATE,
    SELECT_DELETE,
    CLOSE_FORM,
    GO_HOME,

    VERIFY_CREATE,
    VERIFY_RETRIEVE,
    VERIFY_UPDATE,
    VERIFY_DELETE,
    CLOSE_DATA,

    BEFORE_REQUEST,
    AFTER_REQUEST,
}
